### ISSUE TITLE
2023.9.0 shows duplicate names on Tasmota devices

### ISSUE THREAD

**Issue by SirGoodenough** [emontnemery/hatasmota#247]
I just loaded 2023.9.0 and I'm seeing duplicate Tasmota device names.  Didn't see then 2023.8.4.

Running tasmota 13.1 firmware, the latest.

![Screenshot_20230907_203156](https://github.com/emontnemery/hatasmota/assets/47349533/b1525f74-bbd7-451e-853a-fd1cf314b0b2)
![Screenshot_20230907_202926](https://github.com/emontnemery/hatasmota/assets/47349533/f16c8ac0-3255-494c-8c1e-134acb2ab66f)

**Comment by thecode** [comment]
This is due to https://github.com/home-assistant/core/pull/98636 which changed entity names to comply with HA [Entity naming](https://developers.home-assistant.io/docs/core/entity/#entity-naming) guidelines. Issue should be better created at [Home Assistant core](https://github.com/home-assistant/core/issues/new/choose), but to be honest it is probably going to stay like this as this was already finalized to be the standard.

I am using Tasmota as a custom component for now with this change reverted and initially did not want to release it, I have opened the repository, if you have the knowledge how to manually install a custom component you can use it until you find a better solution. I don't promise maintaining it for the long run as this is a short-term solution for me until I figure out how to bypass this.
https://github.com/thecode/ha-tasmota

**Comment by shaulbarlev** [comment]
very annoying indeed.

**Comment by emontnemery** [comment]
This is a result of Tasmota using FriendlyName1 as device name if no device name is configured.

The linked PR #249 makes the integration check if the tasmota device name is same as the tasmota friendly name 1, and if it is, marks that entity as the "main feature of the device" by setting the entity's friendly name to `None`.

**Comment by emontnemery** [comment]
The linked PR only fixes the problem for a device with a single relay where the device itself is unnamed, Home Assistant needs something like https://github.com/home-assistant/architecture/discussions/957 to fix this problem for devices with multiple relays.
