### ISSUE TITLE
Temperature in history graph

### ISSUE THREAD

**Issue by 1igeza** [emontnemery/hatasmota#48]
I'm using new tasmota integration. On "entity card" temperature is shown correctly with unit of mesurment "°C" but in "history graph"  unit of mesurment is "C", so if I have two temperatures on history graph, one from tasmota and second from other sensor, I'm geting two history graphs instead of one. 
Tasmota 9.1.0.1, HA 0.118
![ha](https://user-images.githubusercontent.com/39980292/99579131-0d723880-29de-11eb-840f-1a5ebb65e0c9.png)

**Comment by emontnemery** [comment]
I think this problem could be due to a (now fixed) bug where unit of measurement was incorrectly set to "C" instead of "°C". In this case maybe the first value in the sensor's history has the unit set to "C".

Could you try to remove the entity and have it discovered again and see if the problem goes away?

**Comment by effelle** [comment]
There was a bug with `°C` already fixed on 0.117.5 or 0.117.6.
I did a quick test with a couple of sensors righ now and are both using the correct unit of measure:
![Screenshot 2020-11-18 at 16 45 52](https://user-images.githubusercontent.com/7702766/99579967-b3fa1180-29bd-11eb-834c-2b856c7f61ad.png)
Perhaps you need to delete the old sensor to have the correct history graph?

**Comment by 1igeza** [comment]
Deleting and adding again device fixed this problem. Thanks for your help.
