### ISSUE TITLE
Fade gets reset when controlling my light using the hatasmota entity.

### ISSUE THREAD

**Issue by Wibias** [emontnemery/hatasmota#54]
Hey!

So whats happening is, that when I turn on Fade my light works all fine fading the light on and off. After then I try to control the light over Homeassistant and the fade option is reset.

The Commands I used to accomplish this were:

Fade On
SetOption91 1

**Comment by emontnemery** [comment]
You need to set "transtition" in Home Assistant.
If you want a default transtion for your light, set a default as explained here: https://www.home-assistant.io/integrations/light/#default-turn-on-values

**Comment by emontnemery** [comment]
The Tasmota integration has been updated to not set speed or fade unless `transition` is actively set in the light turn on/off command from HA: https://github.com/home-assistant/core/issues/45620

Or in other words, transition no longer defaults to 0.

**Comment by zrhutto** [comment]
Is it worth changing ``const.py`` so that it calls ``Speed2`` rather than ``Speed`` if a transition is called by Home Assistant?

I’m running that on my own instance, so that the default Fade Speed remains set (Speed2 only changes the Fade Speed for that next action - available in Tasmota as of 9.2.0.7)

**Comment by emontnemery** [comment]
Yes, `speed2` command was added to Tasmota for this exact reason, I'll get it done within the next few days, a PR would also be welcome
